model:
  arch: st_llm_hf
  model_type: minigpt4_vicuna0_btadapter
  use_grad_checkpoint: True
  max_txt_len: 256
  end_sym: "###"
  video_input: "mean"
  llama_model: "/path/to/vicuna-7b"
  ckpt: '/Path/to/prerained_minigpt4_7b.pth'
  q_former_model: /Path/to/blip2_pretrained_flant5xxl.pth
  qformer_text_input: False
  freeze_LLM: False

datasets:
  caption_videochatgpt:
    num_frames: 16
    #video_reader_type: 'rawframe'
  classification_k710:
    num_frames: 16
  classification_ssv2:
    num_frames: 16
  reasoning_next_qa:
    num_frames: 16
  reasoning_clevrer_qa:
    num_frames: 16
  reasoning_clevrer_mc:
    num_frames: 16
  vqa_webvid_qa:
    num_frames: 16

run:
  task: video_text_it
  bf16: True
  tf32: False
  output_dir: "./stllm/output/minigpt4base_avp"
  num_train_epochs: 2
  dataloader_num_workers: 4
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 1
  evaluation_strategy: "no"
  learning_rate: 2e-5
  weight_decay: 0.
  warmup_ratio: 0.03
  lr_scheduler_type: 'cosine'
  logging_steps: 50
  model_max_length: 1024
  #save_steps: 10000 
  save_strategy: "epoch" 
  save_total_limit: 1
  deepspeed: 'stllm/train/zero3.json'